version: "3"
services:
  web:
    restart: always
    build: .
    ports:
      - "8000:8000"
    environment:
     - PYDAL_URI=mysql://root:TzvACtKksypN4cd2@localhost:3306/test?set_encoding=utf8mb4
    stdin_open: true
    tty: true
    depends_on:
      - mysql
    volumes:
       - py4web-data:/home/py4web

  mysql:
    restart: always
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=TzvACtKksypN4cd2
    ports:
      - "3306:3306"
    volumes:
       - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
  py4web-data: